// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzRtEKYPhUNlgcPMLM-LRLDv1e_gYJ7SE',
    appId: '1:272270914159:android:8f9bc5e49b1224932dd39a',
    messagingSenderId: '272270914159',
    projectId: 'vasravitan-ab9e0',
    storageBucket: 'gs://vasravitan-ab9e0.appspot.com',
    authDomain: 'vasravitan-ab9e0.firebaseapp.com',
    measurementId: 'G-SND807S5J5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzRtEKYPhUNlgcPMLM-LRLDv1e_gYJ7SE',
    appId: '1:272270914159:android:8f9bc5e49b1224932dd39a',
    messagingSenderId: '272270914159',
    projectId: 'vasravitan-ab9e0',
    storageBucket: 'gs://vasravitan-ab9e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzRtEKYPhUNlgcPMLM-LRLDv1e_gYJ7SE',
    appId: '1:272270914159:android:8f9bc5e49b1224932dd39a',
    messagingSenderId: '272270914159',
    projectId: 'vasravitan-ab9e0',
    storageBucket: 'gs://vasravitan-ab9e0.appspot.com',
    androidClientId: '719326293072-94b9ruc8463jt5ask057vqm0rbddh2kh.apps.googleusercontent.com',
    iosClientId: '719326293072-sr1h5t5h367lgaid8tujgq68r7vk9um0.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoesShop',
  );
}
